### PR TITLE
toggled slot

### PR DESCRIPTION
**Pull request by michail-peterlis**
created slot for toggled method and moved lambda function to the method.

### CODE REVIEW

**Comment by MichaelVoelkel** [comment]
Where do you see an advantage of using a method here? In particular, why do you choose to use the old type-unsafe SLOT/SIGNAL syntax?

**Comment by michail-peterlis** [comment]
The advantage is to have a slot to use it from outside. I've used the section in one of my projects, and needed the ability to toggle the collapse state from a checkbox in a menu. Thus I've added this method, in a manner like QAbstractButton has a slot toggle. (I just realized I named it incorrectly toggled while should be toggle, fixed). Though I should provide the change, maybe it is useful for others.
For the type-unsafe SLOT/SIGNAL syntax, I actually don't see what there is type-unsafe?!

**Comment by MichaelVoelkel** [comment]
You are right, moving it to a method makes perfect sense!

`SIGNAL` and `SLOT` do no compile-time check whether the signals/slots exist, they only produce a warning during runtime which is why I consider them inferior. Therefore, I prefer `connect(toggleButton, &QToolButton::toggled, this, &Section::toggled);`

If you would be willing to change this, I would accept your pull request

**Comment by michail-peterlis** [comment]
Good point. I didn't know that connect this way would be compile-time checked. Thank you.
See the current commit.

**Comment by MichaelVoelkel** [comment]
Thank you!

**Pull request merged**
